#!/usr/bin/env bash

if [ ! -z "${CONSUL_ADDR}" ]; then
    options=""
    consul_addr="http://${CONSUL_ADDR}"

    if [ ! -z "${CONSUL_TLS}" ] && [ "${CONSUL_TLS}" -eq 1 ]; then
        consul_addr="https://${CONSUL_ADDR}"

        if [ ! -z "${CONSUL_TLSCAFILE}" ]; then
            options="${options} --cacert ${CONSUL_TLSCAFILE}"
        elif [ ! -z "${CONSUL_TLSCAPATH}" ]; then
            options="${options} --capath ${CONSUL_TLSCAPATH}"
        fi

        if [ ! -z "${CONSUL_TLSCERTFILE}" ]; then
            options="${options} --cert ${CONSUL_TLSCERTFILE}"
        fi

        if [ ! -z "${CONSUL_TLSKEYFILE}" ]; then
            options="${options} --key ${CONSUL_TLSKEYFILE}"
        fi

        if [ -z "${CONSUL_TLSVERIFY}" ] || [ "${CONSUL_TLSVERIFY}" -ne 1 ]; then
            options="${options} --insecure"
        fi
    fi

    if [ ! -z "${CONSUL_TOKEN}" ]; then
        options="${options} --header X-Consul-Token:${CONSUL_TOKEN}"
    fi

    status=0

    if [ -f /var/run/container/service.json ]; then
        id=$(jq -r '.ID' /var/run/container/service.json) && \
            [ $(curl -s -w '%{http_code}' --out /dev/null ${options} \
                -X PUT "${consul_addr}/v1/agent/service/deregister/${id}") == "200" ] || status=1
        rm -f /var/run/container/service.json /var/run/container/check.json
    fi

    exit $status
fi
