#!/usr/bin/env bash

if [ ! -z "${CONSUL_ADDR}" ] && [ ! -z "${CONSUL_SERVICENAME}" ] && [ ! -z "${CONSUL_SERVICEPORT}" ]; then
    options=""
    consul_addr="http://${CONSUL_ADDR}"

    if [ ! -z "${CONSUL_TLS}" ] && [ "${CONSUL_TLS}" -eq 1 ]; then
        consul_addr="https://${CONSUL_ADDR}"

        if [ ! -z "${CONSUL_TLSCAFILE}" ]; then
            options="${options} --cacert ${CONSUL_TLSCAFILE}"
        elif [ ! -z "${CONSUL_TLSCAPATH}" ]; then
            options="${options} --capath ${CONSUL_TLSCAPATH}"
        fi

        if [ ! -z "${CONSUL_TLSCERTFILE}" ]; then
            options="${options} --cert ${CONSUL_TLSCERTFILE}"
        fi

        if [ ! -z "${CONSUL_TLSKEYFILE}" ]; then
            options="${options} --key ${CONSUL_TLSKEYFILE}"
        fi

        if [ -z "${CONSUL_TLSVERIFY}" ] || [ "${CONSUL_TLSVERIFY}" -ne 1 ]; then
            options="${options} --insecure"
        fi
    fi

    if [ ! -z "${CONSUL_TOKEN}" ]; then
        options="${options} --header X-Consul-Token:${CONSUL_TOKEN}"
    fi

    status=0

    if [ -f /var/run/container/service.json ]; then
        id=$(jq -r '.ID' /var/run/container/service.json) && \
            name=$(jq -r '.Name' /var/run/container/service.json) && \
            health=$(curl -s ${options} -X GET "${consul_addr}/v1/health/service/${name}" \
                        -G --data-urlencode "passing=true") && \
            service_ids=$(echo "$health"|jq -r '.[].Service.ID') || break

        check=0
        for service_id in $service_ids; do
            if [ "$service_id" == "$id" ]; then
                check=1

                break
            fi
        done

        if [ $check -eq 0 ]; then
            status=1
        fi
    else
        status=1
    fi

    exit $status
fi
