#!/usr/bin/with-contenv sh

ssh-keygen -A

if [ -S /var/run/docker.sock ]; then
    GID=$(stat -c "%g" /var/run/docker.sock)
    GROUP=$(getent group "${GID}"|cut -d ':' -f 1)

    if [ ! -z "${GROUP}" ]; then
        adduser jenkins "${GROUP}"
    else
        addgroup -g "${GID}" -S docker
        adduser jenkins docker
    fi
fi
